# 같은 Network에서의 작동

version: '3'
services:
  app3:
    build:
      context: ./myDocker
      dockerfile: Dockerfile.edu
    networks:
      - lotto
    command:
      - |
        ping app1
  app4:
    build:
      context: ./myDocker
      dockerfile: Dockerfile.edu
    networks:
      - lotto
    command:
      - |
        ping app2

# network
