version: '3'
services:
  app1:
    image: python:3.9-slim
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        touch /mnt/app1file && ls /mnt
    # shared local volume
  app2:
    image: python:3.9-slim
    entrypoint: [ "sh", "-c" ]
    depends_on:
      - app1
    command:
      - |
        touch /mnt/app2file && ls /mnt
    # shared local volume
  app3:
    image: python:3.9-slim
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        touch /mnt/app3file && ls /mnt
    # shared internal volume
  app4:
    image: python:3.9-slim
    entrypoint: [ "sh", "-c" ]
    depends_on:
      - app3
    command:
      - |
        touch /mnt/app4file && ls /mnt
    # shared internal volume

    # volumes
